// <auto-generated />
namespace TONYVU.ENTITY.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixError_22062017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixError_22062017));
        
        string IMigrationMetadata.Id
        {
            get { return "201706220951045_fixError_22062017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
