// <auto-generated />
namespace TONYVU.ENTITY.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tbl_add_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tbl_add_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051642006_tbl_add_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
