// <auto-generated />
namespace TONYVU.ENTITY.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_add_menu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_add_menu));
        
        string IMigrationMetadata.Id
        {
            get { return "201707241644283_db_add_menu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
